spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gimtracker}
spring.datasource.username=${DB_USERNAME:gimuser}
spring.datasource.password=${DB_PASSWORD:gimpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
server.port=${PORT:8080}
